# Generated by Django 4.2.9 on 2026-02-04 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Attendance date')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], help_text='Attendance status (Present/Absent)', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Record creation timestamp')),
                ('employee', models.ForeignKey(help_text='Reference to the employee', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance_employe_c9bb2b_idx'), models.Index(fields=['date'], name='attendance_date_d460ba_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
