# Generated by Django 4.2.9 on 2026-02-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance_employe_c9bb2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance_date_d460ba_idx',
        ),
    ]
