# Generated by Django 4.2.9 on 2026-02-04 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, help_text='Unique employee identifier', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text="Employee's full name", max_length=200)),
                ('email', models.EmailField(db_index=True, help_text="Employee's email address", max_length=254, unique=True)),
                ('department', models.CharField(help_text='Department name', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Record creation timestamp')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
